# Generated by Django 2.2 on 2021-04-09 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='sessions_per_week',
            new_name='evaluations',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='total_chgs',
            new_name='total_charges',
        ),
        migrations.RemoveField(
            model_name='client',
            name='appointment_type',
        ),
        migrations.AddField(
            model_name='client',
            name='no_shows',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='client',
            name='sessions',
            field=models.IntegerField(default='1'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='client',
            name='therapist_who_treats',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treats_client', to='dataApp.User'),
        ),
    ]
