# Generated by Django 3.1.7 on 2021-04-18 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataApp', '0004_auto_20210415_1852'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='therapist_who_treats',
        ),
        migrations.AddField(
            model_name='client',
            name='therapists',
            field=models.ManyToManyField(related_name='clients', to='dataApp.Therapist'),
        ),
    ]
