# Generated by Django 3.1.7 on 2021-04-19 15:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dataApp', '0005_auto_20210418_1559'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='no_show',
            new_name='noshow',
        ),
    ]
